### ISSUE TITLE
Follow the Freedesktop XDG base directory standard

### ISSUE THREAD

**Issue by x80486** [Cloaklet/Cloak#2]
On Linux, `Cloak` currently creates a `.cloaklet.cloak/` folder in the user's home directory. Most applications/programs don't create a folder in the user's home directory any more, but instead use the `Freedesktop XDG` standard – found here: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html.

Using this standard:
- `$XDG_CACHE_HOME` says "temporal/non-essential" files go to `$HOME/.cache/`
- `$XDG_CONFIG_HOME` says "configuration files" go to `$HOME/.config/`
- `$XDG_DATA_HOME` says "data files" go to `$HOME/.local/share/`

This is just a request to consider using this standard. It makes a lot of sense; it is easy for the user to understand, makes it easier to backup / locate / restore / manage / clear user's data, and creates less clutter in the user's home directory.

Thanks in advance...and thanks so much for your hard work on this – it's amazing!

**Comment by JokerQyou** [comment]
I kind of don't like the idea to split "configuration files" from "data files". I've started to work on moving data files to XDG data directory, but the config file is moving together with the database file (into `$XDG_DATA_HOME`).

I'll document data locations in README so users can backup / locate / restore their data. For the "clear" part, I might add a "Reset app data" button to Options dialog.

**Comment by x80486** [comment]
The problem that this will create is that (most of the time) what's in `XDG_DATA_HOME` could be removed at any time. People don't tend to even backup that location.

A different story is `XDG_CONFIG_HOME`.

So it's really not whether one likes it or not, but what's the purpose for each location.

**Comment by JokerQyou** [comment]
I've just released `0.8.0` which follows the XDG spec. In this version, config file and database file are separated to different directories as you suggested. However I choose to keep log file in a sub-directory in `XDG_DATA_HOME`. I've documented all the file locations in README.

Please give it a try and let me know if there are issues with XDG directories handling.
